/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DHT11SensorReader */

#ifndef _Included_DHT11SensorReader
#define _Included_DHT11SensorReader
#ifdef __cplusplus
extern "C" {
#endif
#undef DHT11SensorReader_DTHPIN
#define DHT11SensorReader_DTHPIN 1L
/*
 * Class:     DHT11SensorReader
 * Method:    readData
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_DHT11SensorReader_readData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
